"""Init

Revision ID: 21374f35196d
Revises: 
Create Date: 2026-05-29 10:43:43.313667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21374f35196d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_index(op.f('ix_routes_provider'), 'routes', ['provider'], unique=False)

    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('day_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directions_id'), 'directions', ['id'], unique=False)

    op.create_table('departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('note_symbol', sa.String(), nullable=True),
    sa.Column('note_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departures_id'), 'departures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departures_id'), table_name='departures')
    op.drop_table('departures')
    op.drop_index(op.f('ix_directions_id'), table_name='directions')
    op.drop_table('directions')
    op.drop_index(op.f('ix_routes_provider'), table_name='routes')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
